[build]
nixpacksVersion = "1.38.0"
providers = ["python"]

[phases.setup]
nixPkgs = [
  "python311",
  "gcc",
  "libffi",
  "zlib",
  "openssl",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py"